version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    container_name: tranceDB
    env_file:
      - ./.env
    networks:
      - mynetwork


  backend:
    image: backend
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/trance-backend/.env
    ports:
      - "8000:8000"
    restart: always
    networks:
      - mynetwork
    depends_on:
      - postgres

  frontend:
    image: frontend
    build: ./frontend
    container_name: frontend
    env_file:
      - ./frontend/trance-frontend/.env
    ports:
      - "3000:3000"
    restart: always
    networks:
      - mynetwork
    depends_on:
      - backend



networks:
  mynetwork:
    driver: bridge